apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: vampi-demo
    com.noname.alanc.vampi/vulnerable: true
    com.noname.alanc.traffic/send: true
  name: vampi-demo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vampi-demo
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: vampi-demo
    spec:
      containers:
        envFrom:
          - configMapRef:
              name: vampi-demo-configmap
        image: 491489166083.dkr.ecr.us-east-1.amazonaws.com/alanc/vampi:latest
        name: vampi-demo
        ports:
          - containerPort: 5000
            protocol: TCP
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      restartPolicy: Always

